from django.utils.translation import ugettext_lazy as _

from base import conf

POST_PREFIX = "POST"

POST_VERBOSE_NAME = _("Post")
POST_VERBOSE_NAME_PLURAL = _("Post")

POST_LIST_URL_NAME = POST_PREFIX + conf.LIST_SUFFIX
POST_CREATE_URL_NAME = POST_PREFIX + conf.CREATE_SUFFIX
POST_DETAIL_URL_NAME = POST_PREFIX + conf.DETAIL_SUFFIX
POST_UPDATE_URL_NAME = POST_PREFIX + conf.UPDATE_SUFFIX
POST_DELETE_URL_NAME = POST_PREFIX + conf.DELETE_SUFFIX

